
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jan 03 19:58:16 CET 2023
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SKRR = 20;
  public static final int CAPPIN = 12;
  public static final int AND = 7;
  public static final int FR = 25;
  public static final int DIPPIN = 5;
  public static final int BAG = 27;
  public static final int MOREEQUAL = 14;
  public static final int OR = 8;
  public static final int WHILE = 29;
  public static final int RN = 17;
  public static final int HIGHKEY = 22;
  public static final int BUSSIN = 16;
  public static final int RACK = 26;
  public static final int LESSEQUAL = 10;
  public static final int ID = 31;
  public static final int TBH = 11;
  public static final int CHIEF = 24;
  public static final int DO = 28;
  public static final int STRESSIN = 2;
  public static final int COMMA = 18;
  public static final int LESSTHAN = 9;
  public static final int EOF = 0;
  public static final int VIBIN = 3;
  public static final int MORETHAN = 13;
  public static final int CONST = 32;
  public static final int error = 1;
  public static final int MF = 4;
  public static final int POPPIN = 30;
  public static final int SKRRT = 21;
  public static final int LACKIN = 6;
  public static final int LOWKEY = 23;
  public static final int SUSSIN = 15;
  public static final int BE = 19;
}

